[project]
name = "directory-tree-printer"
dynamic = ["version"]
description = "A Python CLI tool for generating clean directory tree structures."
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [
    { name = "AmirmasoudCS"}
]
dependencies = [
    "pathspec",
    "rich"
]

keywords = [
    "tree",
    "cli",
    "directory",
    "filesystem",
    "terminal"
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Environment :: Console",
    "Operating System :: OS Independent",
]

[project.scripts]
tree-printer = "tree_printer.cli:run"
tp = "tree_printer.cli:run"

[build-system]
requires = [
    "setuptools>=80",
    "setuptools-scm[toml]>=8",
]
build-backend = "setuptools.build_meta"


[tool.setuptools.packages.find]
include = ["tree_printer*"]

[project.urls]
Homepage = "https://github.com/AmirmasoudCS/Tree-Printer"
Repository = "https://github.com/AmirmasoudCS/Tree-Printer"
Issues = "https://github.com/AmirmasoudCS/Tree-Printer/issues"

[project.optional-dependencies]
dev = [
    "build",
    "pytest",
    "pytest-cov",
    "twine",
    "setuptools-scm[toml]>=8",
]

[tool.setuptools_scm]
version_scheme = "guess-next-dev"
local_scheme = "no-local-version"
fallback_version = "0.0.0"