THEMES = {
    "default": {
        "folder": "blue",
        "file": "white",
        "python": "yellow",
        "markdown": "cyan",
        "json": "bright_yellow",
        "image": "magenta",
        "data": "green",
        "document": "red",
        "archive": "bright_black",
        "audio": "bright_green",
        "video": "bright_magenta",
        "web": "bright_blue",
        "javascript": "yellow",
        "config": "bright_cyan",
    },

    "github": {
        "folder": "bright_blue",
        "file": "white",
        "python": "bright_yellow",
        "markdown": "bright_white",
        "json": "yellow",
        "image": "bright_magenta",
        "data": "bright_green",
        "document": "white",
        "archive": "bright_black",
        "audio": "green",
        "video": "magenta",
        "web": "cyan",
        "javascript": "yellow",
        "config": "bright_cyan",
    },

    "dracula": {
        "folder": "bright_magenta",
        "file": "white",
        "python": "yellow",
        "markdown": "cyan",
        "json": "bright_yellow",
        "image": "magenta",
        "data": "green",
        "document": "bright_red",
        "archive": "bright_black",
        "audio": "bright_green",
        "video": "bright_magenta",
        "web": "bright_cyan",
        "javascript": "yellow",
        "config": "bright_blue",
    },

    "monokai": {
        "folder": "bright_blue",
        "file": "white",
        "python": "bright_green",
        "markdown": "bright_cyan",
        "json": "yellow",
        "image": "magenta",
        "data": "green",
        "document": "bright_red",
        "archive": "bright_black",
        "audio": "cyan",
        "video": "bright_magenta",
        "web": "bright_blue",
        "javascript": "bright_yellow",
        "config": "bright_green",
    },

    "nord": {
        "folder": "bright_cyan",
        "file": "white",
        "python": "yellow",
        "markdown": "cyan",
        "json": "bright_yellow",
        "image": "magenta",
        "data": "green",
        "document": "bright_white",
        "archive": "bright_black",
        "audio": "bright_green",
        "video": "bright_magenta",
        "web": "blue",
        "javascript": "yellow",
        "config": "cyan",
    },

    "solarized": {
        "folder": "blue",
        "file": "bright_white",
        "python": "yellow",
        "markdown": "cyan",
        "json": "bright_yellow",
        "image": "magenta",
        "data": "green",
        "document": "red",
        "archive": "bright_black",
        "audio": "green",
        "video": "bright_magenta",
        "web": "bright_blue",
        "javascript": "bright_yellow",
        "config": "cyan",
    },

    "minimal": {
        "folder": "white",
        "file": "white",
        "python": "white",
        "markdown": "white",
        "json": "white",
        "image": "white",
        "data": "white",
        "document": "white",
        "archive": "bright_black",
        "audio": "white",
        "video": "white",
        "web": "white",
        "javascript": "white",
        "config": "white",
    },

    "neon": {
        "folder": "bright_cyan",
        "file": "bright_white",
        "python": "bright_green",
        "markdown": "bright_magenta",
        "json": "bright_yellow",
        "image": "bright_magenta",
        "data": "bright_green",
        "document": "bright_red",
        "archive": "bright_black",
        "audio": "bright_cyan",
        "video": "bright_magenta",
        "web": "bright_blue",
        "javascript": "yellow",
        "config": "bright_cyan",
    },

    "sunset": {
        "folder": "bright_red",
        "file": "bright_white",
        "python": "yellow",
        "markdown": "bright_magenta",
        "json": "bright_yellow",
        "image": "magenta",
        "data": "green",
        "document": "red",
        "archive": "bright_black",
        "audio": "bright_green",
        "video": "bright_red",
        "web": "bright_yellow",
        "javascript": "yellow",
        "config": "bright_magenta",
    }
}
